### ISSUE TITLE
[suggestion] Check if www folder exists

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/stencil-dev-server#8]
I was playing with dev server and i noticed this:

- If you delete the www folder the build will fail cause there is not a folder called www.
- If you delete the ww folder content the build will success cause a folder called www still exists.

The suggestion is maybe check if www folder exists, if not create it, just like ionic serve does (with ionic if i delete the complete folder, on serve will generate a new www folder).

It shows you a page with this content:
```
{
  "error": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "my-awesome-stencil-repo/www"
  }
}
```
I think this can be useful but i leave it to you.

**Comment by jthoms1** [comment]
The dev-server is pretty generic and is not directly tied into the stencil build process.  It was originally meant to be used with stencil build or with an project that might need a static web server for dev.  It is likely that your stencil.config file defines www as the root.

I think what I might do is making a prettier 404 page and have livereload on it so that if the directory gets created it will reload and show the contents.

**Comment by Fdom92** [comment]
Im totally agree with you, forgot that dev server is more generic than only stencil projects, and yes, my stencil.config:
```
exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}
```
A 404 page with a message like "Hey the root folder you definednis not here" and liverolad would be great.

**Comment by jthoms1** [comment]
For stencil based projects this been resolved. The stencil compiler now creates the html file with livereload.

**Comment by elmariofredo** [comment]
@jthoms1 is it? I tried with latest https://github.com/ionic-team/stencil-app-starter and got very same issue.
